# Generated by Django 3.2.9 on 2021-11-25 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ancillaries', '0002_supplier'),
        ('products', '0003_origin_variety'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('product_branding', models.CharField(max_length=40)),
                ('legal_product_description', models.CharField(max_length=40)),
                ('case_count', models.IntegerField()),
                ('weight_per_unit', models.CharField(max_length=20)),
                ('product_code', models.IntegerField()),
                ('delivered_state', models.CharField(choices=[('CH', 'Chilled'), ('AM', 'Ambient')], default='CH', max_length=2)),
                ('product_inner_barcode', models.IntegerField()),
                ('product_outer_barcode', models.IntegerField()),
                ('size_diameter', models.CharField(max_length=40)),
                ('storage_temperature', models.CharField(max_length=40)),
                ('display_until', models.CharField(max_length=20)),
                ('best_before', models.CharField(max_length=20)),
                ('julian_code', models.CharField(max_length=10)),
                ('approved_origins', models.ManyToManyField(to='products.Origin')),
                ('approved_suppliers', models.ManyToManyField(to='ancillaries.Supplier')),
                ('approved_varieties', models.ManyToManyField(to='products.Variety')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
