# Generated by Django 3.2.9 on 2021-12-08 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_auto_20211208_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('packing_equipment_test', models.CharField(max_length=20)),
                ('test_result', models.CharField(choices=[('Operational', 'Operational'), ('Not Operational', 'Not Operational')], default='Not Operational', max_length=20)),
                ('line_leader_trained', models.BooleanField()),
                ('general_staff_trained', models.BooleanField()),
                ('temp_storage_zone', models.CharField(max_length=20)),
                ('storage_space_available', models.BooleanField()),
                ('handling_equipment_available', models.BooleanField()),
                ('packaging_on_site', models.BooleanField()),
                ('raw_material_on_site', models.BooleanField()),
                ('ready_for_product_run', models.BooleanField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
