# Generated by Django 3.2.9 on 2021-12-16 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20211210_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialmodel',
            name='start_date',
        ),
        migrations.AddField(
            model_name='product',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
