# Generated by Django 3.2.9 on 2021-12-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='signature',
            field=models.CharField(max_length=1000000, null=True),
        ),
    ]
