# Generated by Django 3.2.9 on 2022-01-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20220127_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
