# Generated by Django 3.2.9 on 2021-11-25 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancillaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=40)),
                ('supplier_code', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(99999999), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
